set_alarm_detection_sensibility:
  target:
    entity:
      integration: ezviz
      domain: camera
  fields:
    level:
      required: true
      example: 3
      default: 3
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: box
    type_value:
      required: true
      example: "0"
      default: "0"
      selector:
        select:
          options:
            - "0"
            - "3"

wake_device:
  target:
    entity:
      integration: ezviz
      domain: camera

fetch_messages:
  fields:
    serial:
      example: BH7719633
      selector:
        text:
    subtype:
      example: "92"
      default: "92"
      selector:
        text:
    limit:
      example: 20
      default: 20
      selector:
        number:
          min: 1
          max: 50
          mode: box
    date:
      example: "20260923"
      selector:
        text:

fetch_device_info:
  fields:
    serial:
      required: true
      example: BH7719633
      selector:
        text:
